# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newform.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(751, 646)
        self.law1 = QtWidgets.QLabel(Form)
        self.law1.setGeometry(QtCore.QRect(150, 180, 461, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.law1.setFont(font)
        self.law1.setOpenExternalLinks(True)
        self.law1.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.law1.setObjectName("law1")
        self.law2 = QtWidgets.QLabel(Form)
        self.law2.setGeometry(QtCore.QRect(150, 250, 461, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.law2.setFont(font)
        self.law2.setOpenExternalLinks(True)
        self.law2.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.law2.setObjectName("law2")
        self.law3 = QtWidgets.QLabel(Form)
        self.law3.setGeometry(QtCore.QRect(150, 320, 461, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.law3.setFont(font)
        self.law3.setOpenExternalLinks(True)
        self.law3.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.law3.setObjectName("law3")
        self.law4 = QtWidgets.QLabel(Form)
        self.law4.setGeometry(QtCore.QRect(150, 390, 461, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.law4.setFont(font)
        self.law4.setOpenExternalLinks(True)
        self.law4.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.law4.setObjectName("law4")
        self.law5 = QtWidgets.QLabel(Form)
        self.law5.setGeometry(QtCore.QRect(150, 460, 461, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.law5.setFont(font)
        self.law5.setOpenExternalLinks(True)
        self.law5.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.law5.setObjectName("law5")
        self.search_law = QtWidgets.QLineEdit(Form)
        self.search_law.setGeometry(QtCore.QRect(150, 100, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.search_law.setFont(font)
        self.search_law.setText("")
        self.search_law.setClearButtonEnabled(True)
        self.search_law.setObjectName("search_law")
        self.search_btn = QtWidgets.QPushButton(Form)
        self.search_btn.setGeometry(QtCore.QRect(630, 100, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.search_btn.setFont(font)
        self.search_btn.setObjectName("search_btn")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 104, 64, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.law1.setText(_translate("Form", "TextLabel"))
        self.law2.setText(_translate("Form", "TextLabel"))
        self.law3.setText(_translate("Form", "TextLabel"))
        self.law4.setText(_translate("Form", "TextLabel"))
        self.law5.setText(_translate("Form", "TextLabel"))
        self.search_btn.setText(_translate("Form", "조회"))
        self.label.setText(_translate("Form", "키워드"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
